version: 2.1

executors:
  ubunto-16_04:
    docker:
      - image: innovizswt/swt-base:1.0.0-ubuntu-16.04

jobs:
  test:
    parameters:
      os:
        type: executor
      python-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          command: |
            export PATH=$PYENV_ROOT/shims:$PATH
            pyenv install << parameters.python-version >>
            pyenv global << parameters.python-version >> 3.9.1
            python --version
            python envsetup.py
            python manage.py
          name: Test
          
workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              os: [ubunto-16_04]
              python-version: ["3.6.0", "3.9.0"]
