version: 2.1

jobs:
  test:
    docker:
      - image: innovizswt/swt-base:1.0.0-ubuntu-16.04
    steps:
      - checkout
      - run:
          command: |
            source ~/.bashrc && python envsetup.py
            source ~/.bashrc && python manage.py
          name: Test
          
workflows:
  main:
    jobs:
      - test
